name: Build Docling CLI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          architecture: "x64"
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt
            **/pyproject.toml

      - name: Install Docling and dependencies
        run: |
          pip install docling

      - name: Build CLI with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: -m docling.cli
          mode: standalone
          output-dir: build
          # Optional: Enable plugins if needed (e.g., for GUI or extra features)
          # enable-plugins: pyside6

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docling-cli-${{ runner.os }}
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true
